version: "3"
services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    restart: always
    volumes:
      - /data/lychee/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=dbpassword
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    networks:
      - lychee
  lychee:
    image: devvetton/lychee:dev
    container_name: lychee
    restart: always
    depends_on:
      - lychee_db
    volumes:
      - /data/lychee/conf:/conf
      - /data/lychee/uploads:/uploads
      - /data/lychee/sym:/sym
    environment:
      - DB_HOST=lychee_db
      - DB_USERNAME=lychee
      - DB_PASSWORD=dbpassword
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    networks:
      - lychee
    ports:
      - 8000:80
networks:
  lychee:
